export default {
  classForm: {"create": "Create class", "edit": "Edit class", "name": "Class name", "subject": "Subject", "semester": "Semester", "teacher": "Teacher", "capacity": "Capacity", "status": "Lifecycle", "description": "Description", "schedules": "Weekly schedule (Asia/Bangkok)", "add": "Add session", "remove": "Remove", "day": "Day (Monday = 1, Sunday = 7)", "start": "Start time", "end": "End time", "select": "Select…", "noOptions": "Create a subject, semester and active teacher before creating a class.", "invalid": "Check the form fields: {{field}}", "loadError": "Could not load the form.", "draft": "Draft", "open": "Open", "closed": "Closed", "completed": "Completed", "cancelled": "Cancelled"},
  common: { appName: "Classroom", language: "Language", english: "English", vietnamese: "Tiếng Việt", save: "Save", cancel: "Cancel", retry: "Try again", loading: "Loading…", noData: "No data", actions: "Actions", rows: { one: "{{count}} row", other: "{{count}} rows" }, page: "Page {{current}} of {{total}}", rowsPerPage: "Rows per page", home: "Home", logout: "Log out", loggingOut: "Logging out…" },
  auth: { signIn: "Sign in", signUp: "Sign up", welcomeBack: "Welcome back", welcome: "Create your Classroom account", email: "Email", password: "Password", name: "Name", confirmPassword: "Confirm password", rememberMe: "Remember me", forgotPassword: "Forgot password", forgotPasswordDescription: "Enter your email to change your password.", send: "Send", back: "Back", noAccount: "No account?", haveAccount: "Have an account?", or: "or", passwordMismatch: "Passwords don't match", passwordMismatchDescription: "Please make sure both password fields contain the same value.", signInUsing: "Sign in using" },
  resources: { dashboard: "Home", subjects: "Subjects", classes: "Classes", departments: "Departments", semesters: "Semesters", users: "Users", enrollments: "Enrollments" },
  errors: { "CONCURRENT_UPDATE_RETRY": "Concurrent update. Please retry.", "TEACHER_SCHEDULE_CONFLICT": "Teacher has an overlapping class.", "CLASS_SCHEDULE_CONFLICT": "Sessions overlap within this class.", "SEMESTER_NOT_FOUND": "Semester was not found.", "TEACHER_INVALID": "Choose an active teacher.", "LIFECYCLE_TRANSITION_INVALID": "This lifecycle transition is not allowed.", "CAPACITY_BELOW_ACTIVE_ENROLLMENT": "Capacity cannot be below the active enrollment count.", "VALIDATION_ERROR": "Check the form fields.", CLASS_NOT_OPEN: "This class is not open for enrollment.", REGISTRATION_CLOSED: "Registration is outside the allowed period.", STUDENT_INVALID: "The selected account is not an active student.", ALREADY_ENROLLED: "You are already enrolled in this class.", ENROLLMENT_SELF_ONLY: "Students can only manage their own enrollment.", STUDENT_SCHEDULE_CONFLICT: "This class overlaps with one of your enrolled classes.", CLASS_CAPACITY_FULL: "This class is full.", INVITE_INVALID: "This invite code is invalid.", INVITE_EXPIRED: "This invite code has expired.", INVITE_EXHAUSTED: "This invite code has reached its usage limit.", INVITE_RATE_LIMITED: "Too many invite attempts. Please wait and try again.", ENROLLMENT_RETRY_EXHAUSTED: "Enrollment is busy. Please try again.", unknown: "Something went wrong. Please try again.", AUTH_REQUIRED: "Please sign in to continue.", FORBIDDEN: "You do not have permission for this action.", ACCOUNT_INACTIVE: "This account is inactive.", USER_NOT_FOUND: "User not found.", LAST_ACTIVE_ADMIN: "The last active admin cannot be changed.", PREFERENCE_SAVE_FAILED: "Could not save language preference. You can try again." },
  dashboard: { loading: "Loading dashboard…", error: "Could not load dashboard.", from: "From", to: "To", semester: "Semester", openClasses: "Open classes", activeEnrollments: "Active enrollments", capacity: "Capacity", utilization: "Utilization", noData: "No data", legacyUnknown: "{{count}} legacy enrollment(s) have no reliable event date and are excluded from trends.", enrollmentTrend: "Enrollment trend", enrolled: "Enrolled", cancelled: "Cancelled", classesByDepartment: "Classes by department", capacityStatus: "Capacity status", classes: "Classes", userDistribution: "Active users by role", activity: { title: "Recent activity", enrolled: "Enrolled in {{className}}", reactivated: "Re-enrolled in {{className}}", cancelled: "Cancelled enrollment in {{className}}" }, search: "Search" },
  pages: { error: { title: "Page not found.", description: "The page you are looking for does not exist.", backHome: "Back to homepage", info: "The {{action}} page for {{resource}} has not been added." } },
} as const;
