export default {
  classForm: {"create": "Tạo lớp học", "edit": "Sửa lớp học", "name": "Tên lớp", "subject": "Môn học", "semester": "Học kỳ", "teacher": "Giảng viên", "capacity": "Sĩ số tối đa", "status": "Trạng thái lớp", "description": "Mô tả", "schedules": "Lịch hằng tuần (Asia/Bangkok)", "add": "Thêm buổi học", "remove": "Xóa buổi", "day": "Thứ (Thứ Hai = 1, Chủ nhật = 7)", "start": "Giờ bắt đầu", "end": "Giờ kết thúc", "select": "Chọn…", "noOptions": "Cần tạo môn học, học kỳ và giảng viên đang hoạt động trước khi tạo lớp.", "invalid": "Kiểm tra trường: {{field}}", "loadError": "Không tải được biểu mẫu.", "draft": "Bản nháp", "open": "Mở đăng ký", "closed": "Đóng đăng ký", "completed": "Đã hoàn thành", "cancelled": "Đã hủy"},
  common: { appName: "Quản lý lớp học", language: "Ngôn ngữ", english: "English", vietnamese: "Tiếng Việt", save: "Lưu", cancel: "Hủy", retry: "Thử lại", loading: "Đang tải…", noData: "Không có dữ liệu", actions: "Thao tác", rows: { one: "{{count}} dòng", other: "{{count}} dòng" }, page: "Trang {{current}} / {{total}}", rowsPerPage: "Số dòng mỗi trang", home: "Trang chủ", logout: "Đăng xuất", loggingOut: "Đang đăng xuất…" },
  auth: { signIn: "Đăng nhập", signUp: "Đăng ký", welcomeBack: "Chào mừng bạn trở lại", welcome: "Tạo tài khoản Quản lý lớp học", email: "Email", password: "Mật khẩu", name: "Họ và tên", confirmPassword: "Xác nhận mật khẩu", rememberMe: "Ghi nhớ đăng nhập", forgotPassword: "Quên mật khẩu", forgotPasswordDescription: "Nhập email để thay đổi mật khẩu.", send: "Gửi", back: "Quay lại", noAccount: "Chưa có tài khoản?", haveAccount: "Đã có tài khoản?", or: "hoặc", passwordMismatch: "Mật khẩu không khớp", passwordMismatchDescription: "Hãy bảo đảm hai ô mật khẩu có cùng giá trị.", signInUsing: "Đăng nhập bằng" },
  resources: { dashboard: "Trang chủ", subjects: "Môn học", classes: "Lớp học", departments: "Khoa", semesters: "Học kỳ", users: "Người dùng", enrollments: "Đăng ký lớp" },
  errors: { "CONCURRENT_UPDATE_RETRY": "Có cập nhật đồng thời. Vui lòng thử lại.", "TEACHER_SCHEDULE_CONFLICT": "Giảng viên có lớp trùng lịch.", "CLASS_SCHEDULE_CONFLICT": "Các buổi trong lớp bị trùng giờ.", "SEMESTER_NOT_FOUND": "Không tìm thấy học kỳ.", "TEACHER_INVALID": "Chọn giảng viên đang hoạt động.", "LIFECYCLE_TRANSITION_INVALID": "Không thể chuyển sang trạng thái này.", "CAPACITY_BELOW_ACTIVE_ENROLLMENT": "Sĩ số tối đa không được thấp hơn số đăng ký còn hiệu lực.", "VALIDATION_ERROR": "Vui lòng kiểm tra các trường nhập.", CLASS_NOT_OPEN: "Lớp học chưa mở đăng ký.", REGISTRATION_CLOSED: "Đăng ký nằm ngoài thời hạn cho phép.", STUDENT_INVALID: "Tài khoản được chọn không phải sinh viên đang hoạt động.", ALREADY_ENROLLED: "Bạn đã đăng ký lớp này.", ENROLLMENT_SELF_ONLY: "Sinh viên chỉ được quản lý đăng ký của chính mình.", STUDENT_SCHEDULE_CONFLICT: "Lớp này trùng lịch với một lớp bạn đã đăng ký.", CLASS_CAPACITY_FULL: "Lớp học đã đủ sĩ số.", INVITE_INVALID: "Mã mời không hợp lệ.", INVITE_EXPIRED: "Mã mời đã hết hạn.", INVITE_EXHAUSTED: "Mã mời đã hết lượt sử dụng.", INVITE_RATE_LIMITED: "Có quá nhiều lần thử mã mời. Vui lòng chờ rồi thử lại.", ENROLLMENT_RETRY_EXHAUSTED: "Đăng ký đang bận. Vui lòng thử lại.", unknown: "Đã xảy ra lỗi. Vui lòng thử lại.", AUTH_REQUIRED: "Vui lòng đăng nhập để tiếp tục.", FORBIDDEN: "Bạn không có quyền thực hiện thao tác này.", ACCOUNT_INACTIVE: "Tài khoản này đã ngừng hoạt động.", USER_NOT_FOUND: "Không tìm thấy người dùng.", LAST_ACTIVE_ADMIN: "Không thể thay đổi quản trị viên đang hoạt động cuối cùng.", PREFERENCE_SAVE_FAILED: "Không thể lưu tùy chọn ngôn ngữ. Bạn có thể thử lại." },
  dashboard: { loading: "Đang tải bảng điều khiển…", error: "Không thể tải bảng điều khiển.", from: "Từ ngày", to: "Đến ngày", semester: "Học kỳ", openClasses: "Lớp đang mở", activeEnrollments: "Đăng ký còn hiệu lực", capacity: "Tổng sĩ số", utilization: "Mức sử dụng", noData: "Không có dữ liệu", legacyUnknown: "Có {{count}} đăng ký cũ không có ngày sự kiện đáng tin cậy nên không nằm trong xu hướng.", enrollmentTrend: "Xu hướng đăng ký", enrolled: "Đăng ký", cancelled: "Hủy đăng ký", classesByDepartment: "Lớp theo khoa", capacityStatus: "Tình trạng sĩ số", classes: "Lớp học", userDistribution: "Người dùng hoạt động theo vai trò", activity: { title: "Hoạt động gần đây", enrolled: "Đã đăng ký {{className}}", reactivated: "Đã đăng ký lại {{className}}", cancelled: "Đã hủy đăng ký {{className}}" }, search: "Tìm kiếm" },
  pages: { error: { title: "Không tìm thấy trang.", description: "Trang bạn tìm không tồn tại.", backHome: "Về trang chủ", info: "Trang {{action}} cho {{resource}} chưa được thêm." } },
} as const;
